### PR TITLE
Use mruby-tiny-io in favor of mruby-io

### PR DESCRIPTION
**Pull request by katzer**
As the server only requires IO capabilities to read files, the much slimmer mruby-tiny-io might be a good alternative.

### CODE REVIEW

**Comment by matsumotory** [comment]
Thank you for your PR.
What are the merits of changing mruby-io to mruby-tiny-io?

**Comment by katzer** [comment]
The size of the binary. murky-io is pretty great but adds to much if you just want to read a file.

**Comment by matsumotory** [comment]
OK, thanks!

**Comment by katzer** [comment]
@matsumotory Just recognised that mruby-socket depends on murby-io. Changing to tiny-io has no benefit... You can revert my PR...

**Pull request merged**
